name: Deploy to Staging

on:
  push:
    branches: [ "staging" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH key for server connection
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no twycot@www106.your-server.de -p 222 "echo 'SSH connection successful'"