name: Deploy to Staging

on:
  push:
    branches: [ "staging" ]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key for server connection
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Update repository
        run: |
          ssh -o StrictHostKeyChecking=no twycot@www106.your-server.de -p 222 << 'EOF'
            cd /usr/home/twycot/public_html/photobooth/ || exit 1
            git checkout staging || exit 1
            git pull origin staging || exit 1
          EOF
